spring:
  jpa:
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: 'true'
      path: /console
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: password
  application:
    name: interview
